edition = "2021"
newline_style = "Unix"
hard_tabs = true
# tab_spaces = 2

# brace_style = "AlwaysNextLine"
# trailing_semicolon = false

# format_strings = true
# wrap_comments = true
# format_code_in_doc_comments = true

# imports_granularity = "Crate"
# imports_layout = "Vertical"
# group_imports = "StdExternalCrate"

# reorder_impl_items = true
reorder_modules = true
# merge_derives = true

# match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
# match_block_trailing_comma = true

# struct_field_align_threshold = 20
# enum_discrim_align_threshold = 20
use_field_init_shorthand = true
